image:
  repository: kong-docker-kong-brain-immunity-base.bintray.io/kong-brain-immunity
  tag: 1.2.1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: bintray-kong-brain-immunity

waitImage:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent

# These parameters enable collector to send requests to Kong Admin API
kongAdmin:
  # Set this to the Kong Admin API hostname
  host: my-kong-kong-admin
  # Set this to the Kong Admin API port
  servicePort: 8001
  # Set this to the Kong Admin API protocol
  protocol: http
  # Set this to the Kong Admin API token / KONG_PASSWORD
  token:
    valueFrom:
      secretKeyRef:
        name: kong-admin-token-secret
        key: kong-admin-token
  # Set this to the Kong Admin API token / KONG_PASSWORD secret
  # existingSecret: kong-admin-token-secret-just-got-more-secret

collector:
  containerPort: 5000
  # Set a nodePort which is available
  nodePort: 31555
  service:
    type: NodePort
    port: 5000

postgresql:
  ## Set to false if bringing your own postgresql
  enabled: true
  postgresqlUsername: collector
  postgresqlPassword: collector
  postgresqlDatabase: collector
  service:
    port: 5432
    # host: collector-postgresql # uncomment if bringing your own postgresql

redis:
  ## Set to false if bringing your own redis.
  enabled: true
  port: 6379
  password: redis
  # host: collector-redis-master # uncomment if bringing your own redis

ingress:
  enabled: false

# Enable this only for running integration tests
testendpoints:
  enabled: false
